id = "moss"
name = "Moss"
version = "0.0.1"
schema_version = 1
authors = ["whiting <1712428442@qq.com>"]
description = ""
repository = "https://github.com/windwhiterain/moss-lang-zed-extension"

[grammars.moss]
repository = "https://github.com/windwhiterain/tree-sitter-moss"
rev = "master"

[language_servers.moss-language-server]
name = "Moss Language Server"
languages = ["Moss"]
