id = "moss"
name = "Moss"
version = "0.0.1"
schema_version = 1
authors = ["whiting <1712428442@qq.com>"]
description = ""
repository = "https://github.com/windwhiterain/moss-lang-zed-extension"

[grammars.moss]
repository = "https://github.com/windwhiterain/moss-lang"
rev = "34e547b1d4b61834d1da290d55a9cd405f71efed"

[language_servers.moss-language-server]
name = "Moss Language Server"
languages = ["Moss"]
